// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpxwcijeguvvlbehklmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFweHdjaWplZ3V2dmxiZWhrbG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDI3MzksImV4cCI6MjA2NDg3ODczOX0.ApgF-TTJpN0V-XJJCMurSw_vCxXiPIgHhrvH0uT0dH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);